//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedidoSP
    {
        public int IdPedido { get; set; }
        public int IdSubProducto { get; set; }
        public int IdSuministro { get; set; }
        public decimal CantidadSuministroPSP { get; set; }
        public decimal CostoParcialPSP { get; set; }
        public Nullable<int> IdSubPedido { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual SubProducto SubProducto { get; set; }
        public virtual Suministros Suministros { get; set; }
        public virtual SubPedido SubPedido { get; set; }
    }
}
