//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedidoProducto
    {
        public int IdDetallePedidoProducto { get; set; }
        public int IdPedido { get; set; }
        public int IdProducto { get; set; }
        public int IdSubProducto { get; set; }
        public decimal CostoParcial { get; set; }
        public int CantidadPorciones { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual SubProducto SubProducto { get; set; }
    }
}
