//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubProducto()
        {
            this.DetallePedidoProducto = new HashSet<DetallePedidoProducto>();
            this.DetallePedidoSP = new HashSet<DetallePedidoSP>();
            this.DetalleProducto = new HashSet<DetalleProducto>();
            this.DetalleSubProducto = new HashSet<DetalleSubProducto>();
        }
    
        public int IdSubProducto { get; set; }
        public string NombreSubProducto { get; set; }
        public string DescripcionSubProducto { get; set; }
        public decimal PrecioSubProducto { get; set; }
        public decimal CostoSubProducto { get; set; }
        public bool EstadoSubProducto { get; set; }
        public string Instrucciones { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePedidoProducto> DetallePedidoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePedidoSP> DetallePedidoSP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleProducto> DetalleProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleSubProducto> DetalleSubProducto { get; set; }
    }
}
