//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubPedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubPedido()
        {
            this.DetallePedidoP = new HashSet<DetallePedidoP>();
            this.DetallePedidoSP = new HashSet<DetallePedidoSP>();
        }
    
        public int IdSubPedido { get; set; }
        public int IdPedido { get; set; }
        public int IdUsuario { get; set; }
        public byte[] FechaSubPedido { get; set; }
        public string EstadoSubPedido { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePedidoP> DetallePedidoP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallePedidoSP> DetallePedidoSP { get; set; }
        public virtual Pedido Pedido { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
