//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suministros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suministros()
        {
            this.DetalleSubProducto = new HashSet<DetalleSubProducto>();
        }
    
        public int IdSuministro { get; set; }
        public string NombreSuministro { get; set; }
        public string DescripcionSuministro { get; set; }
        public decimal CostoSuministro { get; set; }
        public int IdProveedor { get; set; }
        public bool EstadoSuministro { get; set; }
        public decimal Cantidad { get; set; }
        public string UnidadMedida { get; set; }
        public decimal ExistenciasSuministro { get; set; }
        public decimal PresentacionSuministro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleSubProducto> DetalleSubProducto { get; set; }
        public virtual Proveedores Proveedores { get; set; }
    }
}
